routes/web.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Route;
use App\Mail\InviteUserToOrganization;
use App\Http\Middleware\AdminMiddleware;
use App\Http\Controllers\Admin\SurveyController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AppViewController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Admin\SurveySectionController;
use App\Http\Controllers\Admin\SurveyQuestionController;
use App\Http\Controllers\EmployeeCSVUploadController;
use App\Http\Controllers\Admin\SurveyOptionController;
use App\Http\Controllers\GetStartedController;

Route::get('/', [AppViewController::class, 'welcome'])->name('welcome');
Route::get('/app', [AppViewController::class, 'app'])->name('home');
Route::get('/take-survey/{survey}', [AppViewController::class, 'takeSurvey'])->name('take-survey');
Route::get('/admin', [AppViewController::class, 'admin'])->name('admin')->middleware(AdminMiddleware::class);

Route::get('/logout', [LoginController::class, 'logout']);
Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [RegisterController::class, 'register']);

Route::get('/invite-email', function() {
    return new InviteUserToOrganization(User::find(1), 'test@test.com');
});

Route::post('/upload-employees-csv', EmployeeCSVUploadController::class);

Route::post('/get-started', GetStartedController::class)->name('get-started');

Route::prefix('/admin')->middleware(AdminMiddleware::class)->group(function() {
    Route::resource('/surveys', SurveyController::class)->names('surveys');
    Route::prefix('/surveys')->group(function() {
        Route::resource('/{surveyId}/sections', SurveySectionController::class)->names('survey-sections');
        Route::resource('/{surveyId}/sections/{sectionId}/options', SurveyOptionController::class)->names('survey-options');
        Route::resource('/{surveyId}/sections/{sectionId}/questions', SurveyQuestionController::class)->names('survey-questions');
    });
});

resources/views/admin.blade.php
@extends('layouts.main')

@push('scripts')
  <script src="{{ asset('js/admin.js') }}" defer></script>
@endpush

@section('content')
    <admin-sidebar></admin-sidebar>
    <v-main>
        <v-container fluid>
            <v-row>
                <v-col cols="4">
                    <a href="{{route('surveys.index')}}">
                        <v-card>
                            <v-card-title>Surveys</v-card-title>
                        </v-card>
                    </a>
                </v-col>
            </v-row>
        </v-container>
    </v-main>
@endsection

resources/views/app.blade.php
@extends('layouts.main')

@push('scripts')
  <script src="{{ asset('js/app.js') }}" defer></script>
@endpush

@section('content')
  <app-sidebar></app-sidebar>
  <app-toolbar></app-toolbar>
  <v-main>
    <v-container fluid>
      <v-breadcrumbs
        v-if="$route.meta.breadcrumbs"
        :items="$route.meta.breadcrumbs"
      ></v-breadcrumbs>
      <router-view></router-view>
    </v-container>
  </v-main>
@endsection

resources/views/invite-user-to-organization.blade.php
@php
    $url = "/register?email={$email}";
    if ($name) {
        $url .= "&name={$name}";
    }
    if ($invitedBy) {
        $url .= "&organization={$invitedBy->organization_id}";
    }
@endphp

@component('mail::message')
# Hey, there!

@if ($invitedBy)
    {{$invitedBy->name}} has invited you to join {{config('app.name')}}.
@else
    Thanks for signing up for {{config('app.name')}}!
@endif

@component('mail::button', ['url' => url($url)])
    Set up your account
@endcomponent

Thanks,<br>
{{ config('app.name') }}
@endcomponent

resources/views/take-survey.blade.php
@extends('layouts.main')

@push('scripts')
    <script>
        window.survey = {!! $survey->toJson() !!}
    </script>
  <script src="{{ asset('js/take-survey.js') }}" defer></script>
@endpush

@section('content')
  <v-main>
    <v-container fluid>
      <router-view></router-view>
    </v-container>
  </v-main>
@endsection