routes/web.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Route;
use App\Mail\InviteUserToOrganization;
use App\Http\Middleware\AdminMiddleware;
use App\Http\Controllers\Admin\SurveyController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AppViewController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Admin\SurveySectionController;
use App\Http\Controllers\Admin\SurveyQuestionController;
use App\Http\Controllers\EmployeeCSVUploadController;
use App\Http\Controllers\Admin\SurveyOptionController;
use App\Http\Controllers\GetStartedController;

Route::get('/', [AppViewController::class, 'welcome'])->name('welcome');
Route::get('/app', [AppViewController::class, 'app'])->name('home');
Route::get('/take-survey/{survey}', [AppViewController::class, 'takeSurvey'])->name('take-survey');
Route::get('/admin', [AppViewController::class, 'admin'])->name('admin')->middleware(AdminMiddleware::class);

Route::get('/logout', [LoginController::class, 'logout']);
Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [RegisterController::class, 'register']);

Route::get('/invite-email', function() {
    return new InviteUserToOrganization(User::find(1), 'test@test.com');
});

Route::post('/upload-employees-csv', EmployeeCSVUploadController::class);

Route::post('/get-started', GetStartedController::class)->name('get-started');

Route::prefix('/admin')->middleware(AdminMiddleware::class)->group(function() {
    Route::resource('/surveys', SurveyController::class)->names('surveys');
    Route::prefix('/surveys')->group(function() {
        Route::resource('/{surveyId}/sections', SurveySectionController::class)->names('survey-sections');
        Route::resource('/{surveyId}/sections/{sectionId}/options', SurveyOptionController::class)->names('survey-options');
        Route::resource('/{surveyId}/sections/{sectionId}/questions', SurveyQuestionController::class)->names('survey-questions');
    });
});

app/Models/Survey.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    protected $fillable = ['name'];

    public function sections()
    {
        return $this->hasMany(SurveySection::class);
    }
}

app/Http/Controllers/Admin/SurveyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Survey;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Middleware\AdminMiddleware;
use App\Models\SurveySection;

class SurveyController extends Controller
{

    public function __constructor()
    {
        $this->middleware(AdminMiddleware::class);
    }

    public function index()
    {
        $surveys = Survey::with('sections.questions')->get();
        return view('admin.surveys.index', compact('surveys'));
    }

    public function create()
    {
        return view('admin.surveys.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $survey = Survey::create([
            'name' => $request->name,
        ]);
        return redirect()->route('surveys.show', $survey);
    }

    public function show($id)
    {
        $survey = Survey::with('sections')->find($id);
        return view('admin.surveys.show', compact('survey'));
    }

    public function edit($id)
    {
        $survey = Survey::find($id);
        return view('admin.surveys.edit', compact('survey'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $survey = Survey::Find($id);
        $survey->update([
            'name' => $request->name,
        ]);
        session()->flash('success', 'Survey updated.');
        return redirect()->route('surveys.show', $survey);
    }

    public function destroy($id)
    {
        $survey = Survey::find($id);
        $survey->sections->each(function(SurveySection $section) {
            $section->options()->delete();
            $section->questions()->delete();
        });
        $survey->sections()->delete();
        $survey->delete();
        return redirect()->route('surveys.index');
    }
}

resources/views/admin/surveys/create.blade.php
@component('admin.layout')
    <div class="mb-4 d-flex">
        <a href="{{route('surveys.index')}}">Surveys</a>
        <v-icon>mdi-chevron-right</v-icon>
        <b>Create</b>
    </div>
    <v-row class="justify-center">
        <v-col cols="6">
            <v-card style="width: 600px;">
                <v-card-title>Add Survey</v-card-title>
                <v-card-text>
                    <form action="{{route('surveys.store')}}" method="post">
                        @csrf
                        <v-text-field label="Name" name="name"></v-text-field>
                        <v-btn type="submit">Save</v-btn>
                    </form>
                </v-card-text>
            </v-card>
        </v-col>
    </v-row>
@endcomponent

resources/views/admin/surveys/edit.blade.php
@component('admin.layout')
    <v-row class="justify-center">
        <v-col cols="6">
            <v-card style="width: 600px;">
                <v-card-title>Edit Survey</v-card-title>
                <form action="{{route('surveys.update', $survey)}}" method="post">
                    <v-card-text>
                            @csrf
                            @method('put')
                            <v-text-field label="Name" name="name" value="{{$survey->name}}"></v-text-field>
                        </v-card-text>
                        <v-card-actions>
                            <v-btn type="submit">Save</v-btn>
                            <a class="ml-4" href="{{route('surveys.show', $survey)}}">
                                <v-btn>Cancel</v-btn>
                            </a>
                    </v-card-actions>
                </form>
            </v-card>
        </v-col>
    </v-row>
@endcomponent

resources/views/admin/surveys/index.blade.php
@component('admin.layout')
<h1>All Surveys</h1>
<ul>
    @foreach ($surveys as $survey)
    <li>
        <a href="{{route('surveys.show', $survey)}}">
            {{$survey->name}}
        </a>
    </li>
    @endforeach
</ul>
<a href="{{route('surveys.create')}}">
    <v-btn><v-icon>mdi-plus</v-icon> Create Survey</v-btn>
</a>
@endcomponent

resources/views/admin/surveys/show.blade.php
@component('admin.layout')
    <div class="mb-4 d-flex">
        <a href="{{route('surveys.index')}}">Surveys</a>
        <v-icon>mdi-chevron-right</v-icon>
        <b>{{$survey->name}}</b>
    </div>
    <h1>{{$survey->name}}</h1>
    <a class="mr-4" href="/take-survey/{{$survey->id}}">
        <v-btn>Preview Survey</v-btn>
    </a>
    <a href="{{route('surveys.edit', $survey)}}">
        <v-btn>Edit Name</v-btn>
    </a>
    <form class="d-inline ml-4" action="{{route('surveys.destroy', $survey)}}" method="POST">
        @csrf
        @method('delete')
        <v-btn type="submit" color="error">
            <v-icon>mdi-delete</v-icon>
            Delete
        </v-btn>
    </form>
    <h2>Sections:</h2>
    <ul style="list-style: none;">
        @foreach ($survey->sections as $section)
            <li class="mb-2">
                <a href="{{route('survey-sections.show', ['section' => $section->id, 'surveyId' => $survey->id])}}">
                    {{$section->name}} - ({{$section->questions()->count()}} questions)
                </a>
            </li>
            @endforeach
    </ul>
    <a href="{{route('survey-sections.create', ['surveyId' => $survey->id])}}">
        <v-btn>
            <v-icon>mdi-plus</v-icon> Add Section
        </v-btn>
    </a>
@endcomponent